import * as THREE from 'three';import {OrbitControls} from '/vendor/OrbitControls.js';
const root='/cad/solid-edge-edu06-r02/',data=await fetch(root+'design.json').then(r=>r.json());
const canvas=document.querySelector('canvas'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
const scene=new THREE.Scene();scene.background=null;const camera=new THREE.PerspectiveCamera(35,1,1,4000);camera.up.set(0,0,1);camera.position.set(800,-900,600);const controls=new OrbitControls(camera,canvas);controls.target.set(0,0,240);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xeaffed,0x243c2b,2.4));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(300,-450,700);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-600;key.shadow.camera.right=600;key.shadow.camera.top=800;key.shadow.camera.bottom=-400;key.shadow.camera.far=1800;key.shadow.bias=-.0002;scene.add(key);const fill=new THREE.DirectionalLight(0xc5edc3,1.8);fill.position.set(-300,300,500);scene.add(fill);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(3000,3000),new THREE.MeshStandardMaterial({color:0x10251c,roughness:.9}));floor.position.z=-5;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(1500,60,0x315b40,0x193e2b);grid.rotation.x=Math.PI/2;grid.position.z=-4.7;scene.add(grid);
function stl(buf){const d=new DataView(buf),n=d.getUint32(80,true),v=new Float32Array(n*9);for(let i=0;i<n;i++)for(let j=0;j<9;j++)v[i*9+j]=d.getFloat32(84+i*50+12+j*4,true);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(v,3));g.computeVertexNormals();return g;}
const geometries=new Map(),metadata=new Map(data.parts.map(p=>[p.name,p]));await Promise.all(data.parts.map(async p=>{geometries.set(p.name,stl(await fetch(root+'stl_mm/'+p.name+'.stl').then(r=>r.arrayBuffer())))}));
const meshes=data.items.map(i=>{const p=metadata.get(i.part),ref=p.category.includes('reference'),gear=/gear|pinion|rack/.test(i.part);const mesh=new THREE.Mesh(geometries.get(i.part),new THREE.MeshStandardMaterial({color:ref?0x52616b:gear?0xc8e99d:0x287a5c,roughness:ref?.36:.64,metalness:ref?.45:.06}));mesh.matrixAutoUpdate=false;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData={...i,ref};scene.add(mesh);return mesh});
function mat(a){return new THREE.Matrix4().fromArray(a.flat()).transpose()};function tr(x=0,y=0,z=0){return new THREE.Matrix4().makeTranslation(x,y,z)};function rz(deg){return new THREE.Matrix4().makeRotationZ(THREE.MathUtils.degToRad(deg))};let q={...data.home};let demo=false,open=false,xray=false;
function update(){const f={fixed:new THREE.Matrix4()};for(const j of data.joints)f[j.name]=f[j.parent].clone().multiply(mat(j.origin)).multiply(rz(q[j.name]));f.pinion=tr(40,0,56).multiply(rz(9-3*q.J1));const mg=mat(data.gripperOrigin),d=(60-q.grip)/2;f.Gpinion=f.J6.clone().multiply(mg).multiply(rz(9+d/15*180/Math.PI));f.jawL=f.J6.clone().multiply(mg).multiply(tr(d,-15,3.9));f.jawR=f.J6.clone().multiply(mg).multiply(tr(-d,15,3.9)).multiply(rz(180));meshes.forEach(m=>{m.matrix.copy(f[m.userData.node]).multiply(mat(m.userData.local));m.matrixWorldNeedsUpdate=true});for(const k in q){const o=document.getElementById('out'+k),v=document.getElementById('in'+k);if(o)o.textContent=q[k].toFixed(1)+(k==='grip'?' mm':'°');if(v)v.value=q[k];}window.motionState={q:{...q},loaded:meshes.length,open,xray};}
const names=['Base yaw','Shoulder pitch','Elbow pitch','Forearm roll','Wrist pitch','Tool roll'];const defs=[...data.joints.map((j,i)=>({...j,title:names[i]})),{name:'grip',title:'Jaw opening',motor:'AX-12A · gear & racks',limits:[45,75]}];
for(const j of defs){const el=document.createElement('div');el.className='joint';el.innerHTML=`<label for="in${j.name}">${j.name} · ${j.title}<em id="out${j.name}"></em></label><input id="in${j.name}" type="range" min="${j.limits[0]}" max="${j.limits[1]}" step=".5"><small>${j.motor} · trial CAD range</small>`;document.querySelector('#joints').append(el);el.querySelector('input').addEventListener('input',e=>{demo=false;q[j.name]=Number(e.target.value);update();document.querySelector('#result').textContent='Custom pose · interference not checked';document.querySelector('#pairs').textContent='Use a saved checked pose to see the native CAD result.';});}
document.querySelector('#home').onclick=()=>{demo=false;q={...data.home};update();showResult('home')};document.querySelector('#demo').onclick=()=>{demo=!demo;document.querySelector('#demo').classList.toggle('active',demo)};document.querySelector('#case').onclick=()=>{open=!open;meshes.filter(m=>/^B01_|^B02/.test(m.userData.part)).forEach(m=>m.visible=!open);document.querySelector('#case').textContent=open?'Close base':'Open base';update()};document.querySelector('#xray').onclick=()=>{xray=!xray;for(const m of meshes){m.material.transparent=xray&&!m.userData.ref;m.material.opacity=xray&&!m.userData.ref?.18:1;m.material.depthWrite=!(xray&&!m.userData.ref);}document.querySelector('#xray').classList.toggle('active',xray);update()};
let results=[];try{results=await fetch(root+'motion-checks/results.json').then(r=>r.json())}catch{}
function showResult(name){const r=results.find(x=>x.pose===name);document.querySelector('#result').textContent=r?`${r.pairs.filter(p=>p.confirmed).length} confirmed interference pairs`:'Native check pending';document.querySelector('#checks').textContent=r?'Solid Edge solid-interference test at this saved pose. Contact-only pairs are listed in the report.':'Motion here is commanded kinematics. It does not prove that the mechanism is collision-free.';document.querySelector('#pairs').textContent=r?r.pairs.filter(p=>p.confirmed).map(p=>`${p.a} ↔ ${p.b}`).join(' · '):'';}
for(const p of data.poses){const o=document.createElement('option');o.value=p.name;o.textContent=p.name.replaceAll('_',' ');document.querySelector('#poses').append(o)}document.querySelector('#poses').onchange=e=>{demo=false;q={...data.poses.find(p=>p.name===e.target.value).q};update();showResult(e.target.value)};showResult('home');update();document.querySelector('#loading').remove();
new ResizeObserver(()=>{const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}).observe(canvas.parentElement);function render(t){if(demo){q.J1=40*Math.sin(t/3000);update();document.querySelector('#result').textContent='Yaw preview · intermediate poses unverified';}controls.update();renderer.render(scene,camera);requestAnimationFrame(render)}requestAnimationFrame(render);
