import * as THREE from 'three';
import {OrbitControls} from 'three/addons/OrbitControls.js';
import {EffectComposer} from '../vendor/addons/postprocessing/EffectComposer.js';
import {RenderPass} from '../vendor/addons/postprocessing/RenderPass.js';
import {SSAOPass} from '../vendor/addons/postprocessing/SSAOPass.js';
import {OutputPass} from '../vendor/addons/postprocessing/OutputPass.js';
import {buildModel} from './model.js';
import {SPEC,PARTS,kinematics,gravityTorques} from './spec.js';

const $=id=>document.getElementById(id),stage=$('scene'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const angles=[...SPEC.home],masses={...SPEC.massAssumptionsKg},rows=[],sliders=[],numbers=[],labelEls=[],lines=[],dots=[];
let scene,camera,renderer,composer,ao,orbit,model,dirty=true,width=0,height=0,selected=1,mode='exterior',labelsOn=true,dimensionsOn=false,separation=0,detailOn=false,detailKind='fastener',motion=null,cameraMotion=null;
const svgNS='http://www.w3.org/2000/svg',degree=Math.PI/180;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function fill(input,value){input.style.setProperty('--fill',`${(value-Number(input.min))/(Number(input.max)-Number(input.min))*100}%`);}
function svg(tag){const el=document.createElementNS(svgNS,tag);$('leaders').append(el);return el;}
function notify(){if(!model)return;const p=model.worldTip();$('announcement').textContent=`${SPEC.joints[selected].name} ${Math.round(angles[selected])} degrees. Tool X ${p[0].toFixed(1)}, Y ${p[1].toFixed(1)}, Z ${p[2].toFixed(1)} millimetres.`;}

SPEC.joints.forEach((spec,i)=>{
  const row=document.createElement('div');row.className='joint-row';row.innerHTML=`<div class="joint-top"><button class="joint-name" type="button" aria-label="Select J${i+1} ${spec.name}"><span>J${i+1}</span>${spec.name}</button><label class="number-box"><input type="number" min="${spec.min}" max="${spec.max}" step="1" value="${angles[i]}" aria-label="${spec.name} degrees"><span>°</span></label></div><input type="range" min="${spec.min}" max="${spec.max}" step="1" value="${angles[i]}" aria-label="${spec.name} angle"><div class="range-ends"><span>${spec.min}°</span><span>${spec.max}°</span></div>`;
  $('joints').append(row);rows.push(row);const range=row.querySelector('[type=range]'),number=row.querySelector('[type=number]');sliders.push(range);numbers.push(number);
  row.querySelector('button').addEventListener('click',()=>selectJoint(i));range.addEventListener('input',()=>{stopMotion();selectJoint(i);angles[i]=Number(range.value);sync();});range.addEventListener('change',notify);
  number.addEventListener('change',()=>{stopMotion();selectJoint(i);const n=number.value===''?angles[i]:Number(number.value);angles[i]=clamp(Number.isFinite(n)?n:angles[i],spec.min,spec.max);number.value=Math.round(angles[i]);sync();notify();});
  const label=document.createElement('button');label.className='joint-label';label.type='button';label.setAttribute('aria-label',`J${i+1} ${spec.name} on model`);label.innerHTML=`<strong>J${i+1}</strong><span>${spec.name}</span><span class="angle"></span>`;label.addEventListener('click',()=>{setTab('motion');selectJoint(i);});$('labels').append(label);labelEls.push(label);lines.push(svg('line'));const dot=svg('circle');dot.setAttribute('r','3.5');dots.push(dot);
});
const dimensionMarks=[['upper',SPEC.upper.length],['forearm',SPEC.forearm.length]].map(([part,value])=>{const line=svg('line');line.classList.add('dimension-line');const ticks=[svg('line'),svg('line')];ticks.forEach(t=>t.classList.add('dimension-line'));const label=document.createElement('div');label.className='dimension-label';label.textContent=`${value.toFixed(1)} mm c–c`;$('labels').append(label);return {part,value,line,ticks,label};});

function setTab(name){document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===name;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));$(`panel-${b.dataset.tab}`).hidden=!on;});}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
document.querySelector('.panel-tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const buttons=[...document.querySelectorAll('[data-tab]')];const current=buttons.indexOf(document.activeElement);if(current<0)return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?2:(current+(event.key==='ArrowRight'?1:2))%3;buttons[next].focus();setTab(buttons[next].dataset.tab);});
function selectJoint(i){selected=i;rows.forEach((row,j)=>{row.classList.toggle('active',j===i);row.querySelector('button').setAttribute('aria-pressed',String(j===i));});labelEls.forEach((label,j)=>{label.classList.toggle('active',j===i);label.setAttribute('aria-pressed',String(j===i));});dirty=true;}

PARTS.forEach(part=>{const option=document.createElement('option');option.value=part.id;option.textContent=part.name;$('part-select').append(option);});
function showPart(){const part=PARTS.find(p=>p.id===$('part-select').value);$('part-name').textContent=part.name;$('part-type').textContent=part.type;$('part-note').textContent=part.note;$('part-dimensions').replaceChildren();part.dims().forEach(([label,value])=>{const row=document.createElement('tr');const a=document.createElement('td'),b=document.createElement('td');a.textContent=label;b.textContent=Number(value).toFixed(1)+' mm';row.append(a,b);$('part-dimensions').append(row);});}
$('part-select').value='upper';showPart();$('part-select').addEventListener('change',()=>{showPart();if(detailOn)leaveDetail();});
const massNames={upper:'Upper arm',forearm:'Forearm',wrist:'Wrist module',tool:'Gripper / tool',elbowMotor:'Elbow motor',wristMotor:'Wrist motor'};
Object.entries(massNames).forEach(([key,name])=>{const label=document.createElement('label');label.innerHTML=`${name}<span><input type="number" min="0" max="2000" step="10" value="${masses[key]*1000}" aria-label="Assumed ${name.toLowerCase()} mass in grams">g</span>`;label.querySelector('input').addEventListener('change',e=>{let n=Number(e.target.value);if(!Number.isFinite(n))n=masses[key]*1000;n=clamp(n,0,2000);e.target.value=n;masses[key]=n/1000;updateReadouts();});$('mass-inputs').append(label);});
$('payload').addEventListener('input',e=>{masses.payload=Number(e.target.value)/1000;$('payload-value').textContent=e.target.value+' g';fill(e.target,e.target.value);updateReadouts();});

function exportFile(name,body,type){const blob=new Blob([body],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export-spec').addEventListener('click',()=>exportFile('EDU05-polymer-P03-spec.json',JSON.stringify({...SPEC,currentPoseDegrees:angles,currentMassAssumptionsKg:masses},null,2),'application/json'));
$('export-parts').addEventListener('click',()=>{const rows=[['Part','Dimension','Nominal mm','Status']];PARTS.forEach(part=>part.dims().forEach(([name,value])=>rows.push([part.name,name,value,'Concept; fit unverified'])));exportFile('EDU05-polymer-P03-dimensions.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv');});

function setup(){
  renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;stage.prepend(renderer.domElement);renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label','Detailed 3D plastic manipulator with selectable joints, braided cables, servo and stepper casings, bearings and captive nut bosses.');
  scene=new THREE.Scene();scene.background=new THREE.Color(0x172e24);scene.fog=new THREE.Fog(0x172e24,700,1800);camera=new THREE.PerspectiveCamera(35,1,.5,6000);camera.position.set(510,435,500);
  orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(110,160,0);orbit.enableDamping=true;orbit.dampingFactor=.1;orbit.minDistance=35;orbit.maxDistance=1800;orbit.maxPolarAngle=Math.PI*.49;orbit.addEventListener('change',()=>dirty=true);orbit.addEventListener('start',()=>{cameraMotion=null;document.querySelectorAll('[data-camera]').forEach(b=>b.classList.remove('active'));});
  scene.add(new THREE.HemisphereLight(0xe6fff3,0x23372e,1.0));
  const key=new THREE.DirectionalLight(0xfff3de,2.9);key.position.set(-160,570,320);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-450,right:550,top:500,bottom:-450,near:10,far:1600});key.shadow.normalBias=.3;key.shadow.bias=-.00008;key.shadow.radius=6;scene.add(key);
  const rim=new THREE.DirectionalLight(0xb8ffdf,2.2);rim.position.set(200,320,-400);scene.add(rim);const fillLight=new THREE.DirectionalLight(0xe2ebff,.72);fillLight.position.set(440,130,300);scene.add(fillLight);
  const env=new THREE.Scene();env.background=new THREE.Color(0x263c35);for(const [x,y,z,w,h] of [[0,500,0,700,500],[-450,100,0,120,600],[450,200,300,160,500]]){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide}));p.position.set(x,y,z);p.lookAt(0,0,0);env.add(p);}const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(env,.035).texture;scene.environmentIntensity=.75;pmrem.dispose();env.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(10000,10000),new THREE.MeshStandardMaterial({color:0x0e2118,roughness:.83,metalness:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-.5;floor.receiveShadow=true;scene.add(floor);
  const grid=new THREE.GridHelper(1400,56,0x557e69,0x426853);grid.position.y=-.3;grid.material.transparent=true;grid.material.opacity=.17;scene.add(grid);
  for(const radius of [145,220]){const points=Array.from({length:181},(_,i)=>new THREE.Vector3(radius*Math.cos(i*Math.PI/90),-.15,radius*Math.sin(i*Math.PI/90)));const ring=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x78a58c,transparent:true,opacity:.17}));scene.add(ring);}
  const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d'),fade=ctx.createRadialGradient(64,64,16,64,64,64);fade.addColorStop(0,'#000000ae');fade.addColorStop(.5,'#00000055');fade.addColorStop(1,'#00000000');ctx.fillStyle=fade;ctx.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(280,250),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.2;scene.add(shadow);
  model=buildModel(scene);
  const renderTarget=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,samples:4});composer=new EffectComposer(renderer,renderTarget);composer.addPass(new RenderPass(scene,camera));ao=new SSAOPass(scene,camera,1,1,24);ao.kernelRadius=8;ao.minDistance=.00008;ao.maxDistance=.004;composer.addPass(ao);composer.addPass(new OutputPass());
  selectJoint(selected);sync();new ResizeObserver(resize).observe(stage);resize();$('loading').hidden=true;
  let down;const raycaster=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=raycaster.intersectObject(detailOn?model.detail:model.root,true);let obj=hits.find(h=>h.object.visible)?.object;let part=null;while(obj){if(obj.userData.joint!==undefined){selectJoint(obj.userData.joint);break;}if(!part&&obj.userData.part)part=obj.userData.part;obj=obj.parent;}if(part){$('part-select').value=part;showPart();}});
  renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading').textContent='The 3D view was interrupted. Reload the page to restore it.';});
  window.polymerStudio={getState:()=>({angles:[...angles],tool:model.worldTip(),calculatedTool:kinematics(angles).points[4],torques:gravityTorques(angles,masses),masses:{...masses},mode,labelsOn,dimensionsOn,separation,detailOn,detailKind,selected,playing:!!motion?.frames,internalGeometry:{ribs:model.ribs.length,hardware:model.hardware.length,motors:model.motors.length,covers:model.covers.length,serviceLoops:model.serviceLoops.length},cableEndpointErrorMm:model.cableEndpointError(),skinOpacity:model.skins[0].material.opacity,visibleCovers:model.covers.filter(c=>c.group.visible).length,spec:SPEC})};
  requestAnimationFrame(tick);
}

function sync(){if(model)model.applyPose(angles);angles.slice(0,5).forEach((a,i)=>{sliders[i].value=a;if(document.activeElement!==numbers[i])numbers[i].value=Math.round(a);fill(sliders[i],a);labelEls[i].querySelector('.angle').textContent=Math.round(a)+'°';});$('gripper').value=angles[5];$('gripper-value').textContent=Math.round(angles[5])+' mm';fill($('gripper'),angles[5]);updateReadouts();dirty=true;}
function updateReadouts(){if(!model)return;const p=model.worldTip();['tool-x','tool-y','tool-z'].forEach((id,i)=>$(id).textContent=(Math.abs(p[i])<.05?0:p[i]).toFixed(1));gravityTorques(angles,masses).forEach((t,i)=>$(['torque-shoulder','torque-elbow','torque-wrist'][i]).textContent=Math.abs(t).toFixed(2));}
$('gripper').addEventListener('input',e=>{stopMotion();angles[5]=Number(e.target.value);sync();});
function stopMotion(){motion=null;$('motion-status').textContent='Manual';$('demo-icon').textContent='▶';$('demo-text').textContent='Play motion study';}
const poses={home:SPEC.home,reach:[0,25,-20,-5,0,44],fold:[10,110,-125,35,70,12]};
document.querySelectorAll('[data-pose]').forEach(b=>b.addEventListener('click',()=>{stopMotion();leaveDetail();if(reduced){angles.splice(0,6,...poses[b.dataset.pose]);sync();return;}motion={start:performance.now(),duration:1100,from:[...angles],to:poses[b.dataset.pose]};$('motion-status').textContent='Moving';}));
$('demo').addEventListener('click',()=>{if(motion?.frames){stopMotion();return;}stopMotion();leaveDetail();motion={start:performance.now(),duration:12000,frames:[[...angles],poses.reach,[-40,75,-65,-40,110,8],poses.fold,[...angles]]};$('motion-status').textContent='Demo';$('demo-icon').textContent='■';$('demo-text').textContent='Stop motion study';});
document.addEventListener('keydown',e=>{if(e.key==='Escape')stopMotion();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMotion();});

function setMode(value){mode=value;model?.setMode(mode);if(ao)ao.enabled=mode!=='xray';document.querySelectorAll('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});$('view-caption').textContent='/ '+({exterior:'Exterior',xray:'X-ray',open:'Open covers'})[mode];$('scene-mode').textContent=detailOn?(detailKind==='drives'?'Generic servo + stepper · hardware study':'M3 printed boss · fastening detail'):({exterior:'Assembled exterior',xray:'Transparent shell · internal geometry',open:'Covers removed · internal geometry'})[mode];dirty=true;}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('separation').addEventListener('input',e=>{separation=Number(e.target.value);model?.separate(separation);$('separation-value').textContent=separation+' mm';fill(e.target,separation);dirty=true;});
$('labels-toggle').addEventListener('click',()=>{labelsOn=!labelsOn;$('labels-toggle').classList.toggle('active',labelsOn);$('labels-toggle').setAttribute('aria-pressed',String(labelsOn));dirty=true;});
$('dims-toggle').addEventListener('click',()=>{dimensionsOn=!dimensionsOn;$('dims-toggle').classList.toggle('active',dimensionsOn);$('dims-toggle').setAttribute('aria-pressed',String(dimensionsOn));dirty=true;});

function projection(p){const q=p.clone().project(camera);return {x:(q.x*.5+.5)*width,y:(-.5*q.y+.5)*height,visible:q.z>=-1&&q.z<=1};}
function overlay(){
  const points=model.joints.map((joint,i)=>{const p=new THREE.Vector3();joint.getWorldPosition(p);return {...projection(p),i};});
  const margin=width<500?10:20,minY=width<550?111:96,maxY=height-63;
  [[0,1,2],[3,4]].forEach((ids,side)=>{const list=ids.map(i=>points[i]).sort((a,b)=>a.y-b.y);let last=minY-40;list.forEach(p=>{p.top=Math.max(last+40,clamp(p.y-14,minY,maxY));last=p.top;});const excess=Math.max(0,last-maxY);list.forEach(p=>{const el=labelEls[p.i],on=labelsOn&&!detailOn&&p.visible;el.hidden=!on;lines[p.i].style.display=dots[p.i].style.display=on?'':'none';if(!on)return;const left=side===0?margin:width-margin-el.offsetWidth,top=p.top-excess;el.style.left=left+'px';el.style.top=top+'px';const line=lines[p.i];line.setAttribute('x1',p.x);line.setAttribute('y1',p.y);line.setAttribute('x2',side===0?left+el.offsetWidth:left);line.setAttribute('y2',top+el.offsetHeight/2);dots[p.i].setAttribute('cx',p.x);dots[p.i].setAttribute('cy',p.y);});});
  dimensionMarks.forEach(mark=>{const on=dimensionsOn&&!detailOn;mark.label.hidden=!on;mark.line.style.display=on?'':'none';mark.ticks.forEach(t=>t.style.display=on?'':'none');if(!on)return;const part=model.parts[mark.part],s=SPEC[mark.part];const a=projection(part.localToWorld(new THREE.Vector3(0,s.height/2+18,0))),b=projection(part.localToWorld(new THREE.Vector3(mark.value,s.height/2+18,0)));mark.line.setAttribute('x1',a.x);mark.line.setAttribute('y1',a.y);mark.line.setAttribute('x2',b.x);mark.line.setAttribute('y2',b.y);const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;[a,b].forEach((p,i)=>{const t=mark.ticks[i];t.setAttribute('x1',p.x-dy/len*5);t.setAttribute('y1',p.y+dx/len*5);t.setAttribute('x2',p.x+dy/len*5);t.setAttribute('y2',p.y-dx/len*5);});mark.label.style.left=clamp((a.x+b.x)/2,75,width-75)+'px';mark.label.style.top=clamp((a.y+b.y)/2-10,100,height-50)+'px';});
}

function fitPosition(target,direction){target.updateWorldMatrix(true,true);const bounds=new THREE.Box3(),points=[];target.traverse(o=>{if(o.isMesh){let visible=true,p=o;while(p&&p!==target.parent){if(!p.visible)visible=false;p=p.parent;}if(!visible)return;o.geometry.computeBoundingBox();const b=o.geometry.boundingBox;for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const p=new THREE.Vector3(x,y,z).applyMatrix4(o.matrixWorld);bounds.expandByPoint(p);points.push(p);}}});const centre=bounds.getCenter(new THREE.Vector3());if(bounds.isEmpty())return {centre:orbit.target.clone(),position:camera.position.clone()};const right=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),direction).normalize(),up=new THREE.Vector3().crossVectors(direction,right),tanV=Math.tan(camera.fov*degree/2),tanH=tanV*camera.aspect;let distance=detailOn?45:220;points.forEach(p=>{p.sub(centre);distance=Math.max(distance,Math.abs(p.dot(right))/tanH*1.25+p.dot(direction),Math.abs(p.dot(up))/tanV*1.24+p.dot(direction));});return {centre,position:centre.clone().addScaledVector(direction,distance)};}
function moveCamera(target,direction,instant=false){const fit=fitPosition(target,direction);if(instant||reduced){camera.position.copy(fit.position);orbit.target.copy(fit.centre);cameraMotion=null;dirty=true;return;}cameraMotion={start:performance.now(),from:camera.position.clone(),to:fit.position,fromTarget:orbit.target.clone(),toTarget:fit.centre};}
function leaveDetail(){if(!detailOn)return;detailOn=false;model.detailMode(false);$('scene-mode').textContent='Assembled '+mode;moveCamera(model.root,new THREE.Vector3(.8,.55,1).normalize());}
function cameraView(name){const directions={perspective:[.8,.55,1],front:[0,.06,1],side:[1,.06,0],top:[0,1,.001]};moveCamera(detailOn?model.detail:model.root,new THREE.Vector3(...directions[name]).normalize());document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===name));}
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>cameraView(b.dataset.camera)));
$('fit').addEventListener('click',()=>{leaveDetail();cameraView('perspective');});
function focusPart(){const id=$('part-select').value;if(id==='fastener'||id==='drives'){detailOn=true;detailKind=id;model.detailMode(true,id);setMode('exterior');moveCamera(model.detail,new THREE.Vector3(id==='drives'?.32:.6,.45,1).normalize());}else{leaveDetail();moveCamera(model.parts[id],new THREE.Vector3(.55,.35,1).normalize());}dirty=true;}
$('focus-part').addEventListener('click',focusPart);$('show-fastener').addEventListener('click',()=>{$('part-select').value='fastener';showPart();focusPart();});
$('show-drives').addEventListener('click',()=>{setTab('parts');$('part-select').value='drives';showPart();focusPart();});
function resize(){const changed=width!==stage.clientWidth||height!==stage.clientHeight;width=stage.clientWidth;height=stage.clientHeight;if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();composer?.setSize(width,height);if(changed)moveCamera(detailOn?model.detail:model.root,camera.position.clone().sub(orbit.target).normalize(),true);dirty=true;}

function tick(time){requestAnimationFrame(tick);if(document.hidden)return;if(motion){let t=clamp((time-motion.start)/motion.duration,0,1),from,to,s;if(motion.frames){const pos=t*(motion.frames.length-1),i=Math.min(Math.floor(pos),motion.frames.length-2);from=motion.frames[i];to=motion.frames[i+1];s=pos-i;}else{from=motion.from;to=motion.to;s=t;}s=s*s*(3-2*s);angles.forEach((_,i)=>angles[i]=from[i]+(to[i]-from[i])*s);sync();if(t===1){stopMotion();notify();}}
  if(cameraMotion){const t=clamp((time-cameraMotion.start)/650,0,1),s=t*t*(3-2*t);camera.position.lerpVectors(cameraMotion.from,cameraMotion.to,s);orbit.target.lerpVectors(cameraMotion.fromTarget,cameraMotion.toTarget,s);dirty=true;if(t===1)cameraMotion=null;}orbit.update();if(dirty){composer.render();overlay();dirty=false;}}

fill($('payload'),100);fill($('separation'),0);
try{setup();}catch(error){console.error(error);$('loading').hidden=false;$('loading').textContent='The 3D renderer could not start. Enable WebGL 2 in your browser and reload this page.';$('app-status').textContent='3D renderer unavailable';}



